In [1]:
import pandas as pd
from pathlib import Path

csv_path = Path("data") / "RMBR4-2_export_test.csv"

robot_data = pd.read_csv(csv_path)

robot_data.head()

,Trait,Axis #1,Axis #2,Axis #3,Axis #4,Axis #5,Axis #6,Axis #7,Axis #8,Axis #9,Axis #10,Axis #11,Axis #12,Axis #13,Axis #14,Time
0,current,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,2022-10-17T12:18:23.660Z
1,current,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,2022-10-17T12:18:25.472Z
2,current,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,2022-10-17T12:18:27.348Z
3,current,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,2022-10-17T12:18:29.222Z
4,current,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,2022-10-17T12:18:31.117Z

In [2]:
print("Rows:", len(robot_data))
print("Columns:", robot_data.columns.tolist())

Rows: 39672
Columns: ['Trait', 'Axis #1', 'Axis #2', 'Axis #3', 'Axis #4', 'Axis #5', 'Axis #6', 'Axis #7', 'Axis #8', 'Axis #9', 'Axis #10', 'Axis #11', 'Axis #12', 'Axis #13', 'Axis #14', 'Time']

In [3]:
robot_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39672 entries, 0 to 39671
Data columns (total 16 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Trait     39672 non-null  object
 1   Axis #1   39672 non-null  float64
 2   Axis #2   39672 non-null  float64
 3   Axis #3   39672 non-null  float64
 4   Axis #4   39672 non-null  float64
 5   Axis #5   39672 non-null  float64
 6   Axis #6   39672 non-null  float64
 7   Axis #7   39672 non-null  float64
 8   Axis #8   39672 non-null  float64
 9   Axis #9   0 non-null      float64
 10  Axis #10  0 non-null      float64
 11  Axis #11  0 non-null      float64
 12  Axis #12  0 non-null      float64
 13  Axis #13  0 non-null      float64
 14  Axis #14  0 non-null      float64
 15  Time      39672 non-null  object
dtypes: float64(14), object(2)
memory usage: 4.8+ MB

In [4]:
robot_data.head()

,Trait,Axis #1,Axis #2,Axis #3,Axis #4,Axis #5,Axis #6,Axis #7,Axis #8,Axis #9,Axis #10,Axis #11,Axis #12,Axis #13,Axis #14,Time
0,current,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,2022-10-17T12:18:23.660Z
1,current,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,2022-10-17T12:18:25.472Z
2,current,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,2022-10-17T12:18:27.348Z
3,current,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,2022-10-17T12:18:29.222Z
4,current,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,2022-10-17T12:18:31.117Z

In [5]:
from src.data_collection.streaming_simulator import StreamingSimulator

In [6]:
ss = StreamingSimulator("data/RMBR4-2_export_test.csv")

In [7]:
ss

In [8]:
ss.nextDataPoint()

,Trait,Axis #1,Axis #2,Axis #3,Axis #4,Axis #5,Axis #6,Axis #7,Axis #8,Axis #9,Axis #10,Axis #11,Axis #12,Axis #13,Axis #14,Time
0,current,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,2022-10-17T12:18:23.660Z

In [9]:
ss.nextDataPoint()

,Trait,Axis #1,Axis #2,Axis #3,Axis #4,Axis #5,Axis #6,Axis #7,Axis #8,Axis #9,Axis #10,Axis #11,Axis #12,Axis #13,Axis #14,Time
1,current,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,2022-10-17T12:18:25.472Z

In [10]:
from src.database_service.database_service_agent import DatabaseService

In [11]:
db = DatabaseService()

In [12]:
db.create_table()

In [13]:
ss.nextDataPoint()

,Trait,Axis #1,Axis #2,Axis #3,Axis #4,Axis #5,Axis #6,Axis #7,Axis #8,Axis #9,Axis #10,Axis #11,Axis #12,Axis #13,Axis #14,Time
2,current,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,2022-10-17T12:18:27.348Z

In [14]:
data_point = ss.nextDataPoint()

data_point

,Trait,Axis #1,Axis #2,Axis #3,Axis #4,Axis #5,Axis #6,Axis #7,Axis #8,Axis #9,Axis #10,Axis #11,Axis #12,Axis #13,Axis #14,Time
3,current,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,2022-10-17T12:18:29.222Z

In [15]:
db.insert_data(data_point)

### Make a simple test with several records

-- Before building the live dashboard, let's make sure the streaming + database works.

In [16]:
for i in range(5):

    data_point = ss.nextDataPoint()

    if data_point is None:
        break

    db.insert_data(data_point)

    print("Inserted record", i + 1)

Inserted record 1
Inserted record 2
Inserted record 3
Inserted record 4
Inserted record 5

In [17]:
print(robot_data.columns.tolist())
robot_data.head(3)

['Trait', 'Axis #1', 'Axis #2', 'Axis #3', 'Axis #4', 'Axis #5', 'Axis #6', 'Axis #7', 'Axis #8', 'Axis #9', 'Axis #10', 'Axis #11', 'Axis #12', 'Axis #13', 'Axis #14', 'Time']

,Trait,Axis #1,Axis #2,Axis #3,Axis #4,Axis #5,Axis #6,Axis #7,Axis #8,Axis #9,Axis #10,Axis #11,Axis #12,Axis #13,Axis #14,Time
0,current,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,2022-10-17T12:18:23.660Z
1,current,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,2022-10-17T12:18:25.472Z
2,current,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,2022-10-17T12:18:27.348Z

In [18]:
robot_data["Trait"].value_counts()

Trait
current    39672
Name: count, dtype: int64

In [19]:
robot_data.groupby("Trait").size()

Trait
current    39672
dtype: int64

In [20]:
robot_data[["Trait", "Axis #1", "Axis #2", "Axis #3", "Axis #4", "Axis #5", "Axis #6", "Axis #7", "Axis #8"]].head(20)

,Trait,Axis #1,Axis #2,Axis #3,Axis #4,Axis #5,Axis #6,Axis #7,Axis #8
0,current,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,current,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,current,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,current,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,current,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,current,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,current,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,current,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,current,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,current,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,current,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,current,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,current,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,current,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,current,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,current,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,current,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,current,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,current,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,current,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0